// Writes src/clientLogos.ts from whatever is in public/logos/. Drop a client's
// logo there as <slug>.svg or <slug>.png and it replaces that client's wordmark
// in the proof wall on the next build. Slugs are listed in the scene.
const fs = require('fs'), path = require('path');
const dir = path.join(__dirname, '..', 'public', 'logos');
const files = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => /\.(svg|png)$/i.test(f)) : [];
const map = {};
for (const f of files) map[f.replace(/\.(svg|png)$/i, '').toLowerCase()] = 'logos/' + f;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'clientLogos.ts'),
  `/* GENERATED by scripts/scan-logos.js from public/logos. Do not edit. */\nexport const CLIENT_LOGOS: Record<string, string> = ${JSON.stringify(map, null, 2)};\n`);
console.log(`${files.length} client logo file(s): ${files.join(', ') || 'none, wordmarks will be used'}`);
